version: '2'

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    logging:
      driver: none
    tmpfs: "/datalog"
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events
      MYSQL_USER: events
      MYSQL_PASSWORD: events
    logging:
      driver: none

  webhooks_web:
    env_file:
      - src/.env
    environment:
      KAFKA_BROKER_LIST: kafka:9092
      KAFKA_GROUP_ID: events
      EVENT_TOPIC: events

      MYSQL_HOST: db
      MYSQL_DATABASE: events
      MYSQL_USER: events
      MYSQL_PASSWORD: events
    build: .
    volumes:
      - ./src:/webhook-app/src
      - /webhook-app/src/node_modules
      - ./db:/webhook-app/db
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - kafka
      - db
